name: Build test BioSimulators interface and release to BioSimulators registry

on:
  push:
  workflow_dispatch:

jobs:
  buildTestDeploy:
    name: Build, test, and deploy BioSimulators interface
    runs-on: ubuntu-latest
    steps:
      #############################################
      ## Checkout repository
      #############################################
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      #############################################
      ## Install package and its dependencies
      #############################################
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python
          key: ${{ runner.os }}-pip-${{ hashFiles('biosimulators/requirements.txt') }}-${{ hashFiles('biosimulators/requirements.optional.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      #############################################
      ## Lint
      #############################################
      - name: Install flake8
        run: python -m pip install flake8

      - name: Lint the package
        run: |
          cd biosimulators
          python -m flake8

      #############################################
      ## Get and sync version number
      #############################################
      - id: get-version-number
        name: Get version number
        run: |
          VERSION=$(cat src/libsbmlsim/version.h | grep LIBSBMLSIM_DOTTED_VERSION | cut -d '"' -f 2)
          echo "::set-output name=version::$VERSION"

      - name: Synchronize Python package with  version number
        env:
            VERSION: ${{ steps.get-version-number.outputs.version }}
        run: echo "__version__ = '${VERSION}'" > biosimulators/biosimulators_libsbmlsim/_version.py

      #############################################
      ## Build Docker image
      #############################################
      - name: Build Docker image
        run: |
          REVISION=$(git rev-parse HEAD)
          CREATED=$(date --rfc-3339=seconds | sed 's/ /T/')
          docker build \
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            --label org.opencontainers.image.revision=${REVISION} \
            --label org.opencontainers.image.created=${CREATED} \
            --build-arg VERSION=${{ steps.get-version-number.outputs.version }} \
            --tag ghcr.io/${{ github.repository }}/libsbmlsim:${{ steps.get-version-number.outputs.version }} \
            --tag ghcr.io/${{ github.repository }}/libsbmlsim:latest \
            -f biosimulators/Dockerfile \
            .

      #############################################
      ## Test
      #############################################
      - name: Run the tests
        run: |
          cwd=$(pwd)
          docker run \
              --rm \
              --entrypoint bash \
              --mount type=bind,source=${cwd},target=/root/libsbmlsim \
              --workdir /root/libsbmlsim/biosimulators \
              ghcr.io/${{ github.repository }}/libsbmlsim:latest \
              -c "
                  pip install pytest pytest-cov \
                  && pip install -r tests/requirements.txt \
                  && python -m pytest tests/ --cov biosimulators_libsbmlsim
              "

      #############################################
      ## Release to BioSimulators registry
      #############################################

      # build Docker image and push to GitHub Container Registry
      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        run: |
          docker login ghcr.io \
            --username ${{ secrets.GHCR_USERNAME }} \
            --password ${{ secrets.GHCR_TOKEN }}
          docker push ghcr.io/${{ github.repository }}/libsbmlsim:${{ steps.get-version-number.outputs.version }}
          docker push ghcr.io/${{ github.repository }}/libsbmlsim:latest

      # Submit to BioSimulators registry
      - name: Submit to BioSimulators registry
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        run: |
          REVISION=$(git rev-parse HEAD)
          curl \
            -X POST \
            -u ${{ secrets.BIOSIMULATORS_GH_USERNAME }}:${{ secrets.BIOSIMULATORS_GH_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/biosimulators/Biosimulators/issues \
            -d "{\"labels\": [\"Validate/submit simulator\"], \"title\": \"Submit LibSBMLsim ${{ steps.get-version-number.outputs.version }}\", \"body\": \"---\nid: libsbmlsim\nversion: ${{ steps.get-version-number.outputs.version }}\nspecificationsUrl: https://raw.githubusercontent.com/${{ github.repository }}/${REVISION}/biosimulators.json\nspecificationsPatch:\n  version: ${{ steps.get-version-number.outputs.version }}\n  image:\n    url: ghcr.io/${{ github.repository }}/libsbmlsim:${{ steps.get-version-number.outputs.version }}\nvalidateImage: true\ncommitSimulator: true\n\n---\"}"
